/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import javax.swing.SpinnerModel;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author LENOVO
 */
public class AddRentCarView extends javax.swing.JFrame {

    /**
     * Creates new form AddRentCarView
     */
    public AddRentCarView() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        duration = new javax.swing.ButtonGroup();
        btnback = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        rbother = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablecar = new javax.swing.JTable();
        SpinnerModel sm = new SpinnerNumberModel(2, 2, 7, 1);
        sduration = new javax.swing.JSpinner(sm);
        jLabel10 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tfid = new javax.swing.JTextField();
        lcost = new javax.swing.JLabel();
        tfname = new javax.swing.JTextField();
        btnrent = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        rb6h = new javax.swing.JRadioButton();
        rb12h = new javax.swing.JRadioButton();
        rb24h = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnback.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btnback.setForeground(new java.awt.Color(53, 24, 90));
        btnback.setText("< Back");
        btnback.setBorderPainted(false);
        btnback.setContentAreaFilled(false);
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel1.setText("Car Rent");

        duration.add(rbother);
        rbother.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        rbother.setForeground(new java.awt.Color(53, 24, 90));
        rbother.setText("Other");
        rbother.setContentAreaFilled(false);
        rbother.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbotherActionPerformed(evt);
            }
        });

        tablecar.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        tablecar.setForeground(new java.awt.Color(53, 24, 90));
        tablecar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Brand", "Type", "License", "Cost (1h)", "Available"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablecar.setRowHeight(20);
        tablecar.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tablecar);

        sduration.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        sduration.setEnabled(false);

        jLabel10.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(53, 24, 90));
        jLabel10.setText("days");

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel6.setText("ID");

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel9.setText("Cost");

        tfid.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        tfid.setForeground(new java.awt.Color(53, 24, 90));
        tfid.setEnabled(false);

        lcost.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lcost.setText("0");

        tfname.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        tfname.setForeground(new java.awt.Color(53, 24, 90));

        btnrent.setBackground(new java.awt.Color(53, 24, 90));
        btnrent.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btnrent.setForeground(new java.awt.Color(255, 255, 255));
        btnrent.setText("RENT");

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel7.setText("Name");

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel8.setText("Duration");

        duration.add(rb6h);
        rb6h.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        rb6h.setForeground(new java.awt.Color(53, 24, 90));
        rb6h.setText("6h");
        rb6h.setContentAreaFilled(false);

        duration.add(rb12h);
        rb12h.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        rb12h.setForeground(new java.awt.Color(53, 24, 90));
        rb12h.setText("12h");
        rb12h.setContentAreaFilled(false);
        rb12h.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb12hActionPerformed(evt);
            }
        });

        duration.add(rb24h);
        rb24h.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        rb24h.setForeground(new java.awt.Color(53, 24, 90));
        rb24h.setText("24h");
        rb24h.setContentAreaFilled(false);
        rb24h.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb24hActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnback)
                        .addGap(119, 119, 119)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6)
                            .addComponent(tfid, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(tfname, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rb6h)
                                .addGap(44, 44, 44)
                                .addComponent(rb12h)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(rb24h))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbother)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(sduration, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lcost, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnrent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(btnback))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfid, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfname, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rb6h, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rb12h, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rb24h, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(sduration, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel10))
                            .addComponent(rbother, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lcost, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnrent, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnbackActionPerformed

    private void rbotherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbotherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbotherActionPerformed

    private void rb12hActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb12hActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb12hActionPerformed

    private void rb24hActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb24hActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb24hActionPerformed
    public String getId(){
        return tfid.getText();
    }
    public String getAName(){
        return tfname.getText();
    }
    public int getDuration(){
        return (int) sduration.getValue();
    }
    public int getCost(){
        return Integer.parseInt(lcost.getText());
    }
    public void setForm(String id){
        tfid.setText(id);
    }
    public void resetForm(){
        tfid.setText("");
        tfname.setText("");
        duration.clearSelection();
        lcost.setText("0");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnback;
    public javax.swing.JButton btnrent;
    private javax.swing.ButtonGroup duration;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel lcost;
    public javax.swing.JRadioButton rb12h;
    public javax.swing.JRadioButton rb24h;
    public javax.swing.JRadioButton rb6h;
    public javax.swing.JRadioButton rbother;
    public javax.swing.JSpinner sduration;
    public javax.swing.JTable tablecar;
    private javax.swing.JTextField tfid;
    private javax.swing.JTextField tfname;
    // End of variables declaration//GEN-END:variables
}
